v5b
ESP3D instead of MOD_WIFI.

SanityCheck.h:2972:6: error: #error "TFT_LVGL_UI requires TFT_RES_480x320.", TFT_COLOR_UI builds okay still.

No UART feedback with v5b at all, M118P0, P1 & P2 all get echoed to host connected via USB.  No esphome temperature feedback.