v5
M118 work around added.

Add M118 commands from UI for testing

v5a changes

Changes and calibration for QQSP, August 2022

v5b

ESP3D instead of MOD_WIFI.

SanityCheck.h:2972:6: error: #error "TFT_LVGL_UI requires TFT_RES_480x320.", TFT_COLOR_UI builds okay still.

No UART feedback with v5b at all, M118P0, P1 & P2 all get echoed to host connected via USB.  No esphome temperature feedback.

v5c

wifi rx/tx works

M118 only blank lines.